In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[10, 26], [3, 5], [13, 10], [2, 10, 7], [19, 27, 25], [18, 26], [22, 27, 27], [26, 11], [26, 26], [17, 18]]


In [3]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[10 26  0  0]
 [ 3  5  0  0]
 [13 10  0  0]
 [ 2 10  7  0]
 [19 27 25  0]
 [18 26  0  0]
 [22 27 27  0]
 [26 11  0  0]
 [26 26  0  0]
 [17 18  0  0]]


In [4]:
embeding_size=5
model = Sequential()
model.add(Embedding(vocab_size,embeding_size,input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation="sigmoid"))

/opt/anaconda3/envs/tf_env/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [7]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
model.fit(padded_reviews,sentiment,epochs=50)

Epoch 1/50


2026-02-22 09:33:23.662560: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 813ms/step - accuracy: 0.8000 - loss: 0.6803
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8000 - loss: 0.6791
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8000 - loss: 0.6779
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9000 - loss: 0.6767
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9000 - loss: 0.6755
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9000 - loss: 0.6743
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9000 - loss: 0.6731
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9000 - loss: 0.6718
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9000 - loss: 0.6706
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9000 - loss: 0.6694
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9000 - loss: 0.6682
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9000 - loss: 0.6670
Epoch 13/50

In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 4, 5)           │           150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 20)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 515 (2.02 KB)

 Trainable params: 171 (684.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 344 (1.35 KB)

In [10]:
model.get_layer("embedding").get_weights()[0]


array([[-0.04892082,  0.00533567, -0.04702638, -0.02388949, -0.01476642],
       [ 0.02004831, -0.02567918, -0.02698051,  0.03126892,  0.00654131],
       [ 0.00420066, -0.09745923,  0.06426604, -0.07485536,  0.02420186],
       [ 0.04325721, -0.06723373,  0.02662787, -0.01817758,  0.04366931],
       [ 0.03571245,  0.03070452,  0.02033437,  0.03112557, -0.00040984],
       [-0.08823246,  0.06364625, -0.04430408, -0.03517823, -0.07623135],
       [ 0.02538475,  0.00098169, -0.02983314, -0.00425231,  0.03476793],
       [ 0.00645168,  0.08129917,  0.07468767, -0.04872588,  0.01517831],
       [ 0.04624107,  0.00099935, -0.01720262, -0.04122519,  0.02578553],
       [ 0.00834956, -0.02481472,  0.01434144,  0.00559286,  0.02833894],
       [-0.08142461, -0.05848171, -0.0313452 , -0.11549469, -0.05751179],
       [ 0.07155809, -0.06907114,  0.06769689,  0.07600684,  0.06657413],
       [-0.0348944 ,  0.04750008, -0.01070632,  0.03768014,  0.00828646],
       [ 0.07151063, -0.0323128 ,  0.0